name: color_blind_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  firebase_core: ^2.15.0
  fluttertoast: ^8.2.2
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  
  

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  
  
flutter_native_splash:
  android: true
  ios: true 
  background_image: "images/background.jpeg"
  
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
